### ISSUE TITLE
Problem with 1.14.4 and unfinished staff

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#35]
The following ABC-code does not render properly on 1.14.4

Issue was introduced in commit 8cbc097

````
X:3045
F:3045_unreferenced-voices
T:unreferenced voices
C:
S:
M:4/4
L:1/4
Q:1/4=120
K:C
%
%
%%score 1 2 3 4
%
V:1 clef=treble name="Sopran" snm="S"
c
V:2 clef=treble name="Alto" snm="A"
B
V:3 clef=bass name="Tenor" snm="T"
C
V:4 clef=bass name="Bass" snm="B"
````

I get 

![screenshot_985](https://user-images.githubusercontent.com/2022976/31779603-cb538cae-b4f3-11e7-9b0f-471b4a202bd4.jpg)

Also get messages on console

jquery-3.0.0.min.js?dev:3 Error: <path> attribute d: Expected number, "mNaN 161.00v21.00".
oa @ jquery-3.0.0.min.js?dev:3
jquery-3.0.0.min.js?dev:3 Error: <text> attribute x: Expected length, "NaN".
oa @ jquery-3.0.0.min.js?dev:3
jquery-3.0.0.min.js?dev:3 Error: <rect> attribute x: Expected length, "NaN".
oa @ jquery-3.0.0.min.js?dev:3
jquery-3.0.0.min.js?dev:3 Error: <use> attribute x: Expected length, "NaN".
oa @ jquery-3.0.0.min.js?dev:3
jquery-3.0.0.min.js?dev:3 Error: <path> attribute d: Expected number, "mNaN 201.00v21.00".
oa @ jquery-3.0.0.min.js?dev:3
jquery-3.0.0.min.js?dev:3 Error: <text> attribute x: Expected length, "NaN".
oa @ jquery-3.0.0.min.js?dev:3
jquery-3.0.0.min.js?dev:3 Error: <rect> attribute x: Expected length, "NaN".
oa @ jquery-3.0.0.min.js?dev:3
jquery-3.0.0.min.js?dev:3 Error: <path> attribute d: Expected number, "mNaN 262.00v21.00".
oa @ jquery-3.0.0.min.js?dev:3
jquery-3.0.0.min.js?dev:3 Error: <text> attribute x: Expected length, "NaN".
oa @ jquery-3.0.0.min.js?dev:3
jquery-3.0.0.min.js?dev:3 Error: <rect> attribute x: Expected length, "NaN".

**Comment by moinejf** [comment]
This should be fixed by commit 8155c6984e84dcceb235520c901763164af4027c.

**Comment by bwl21** [comment]
Sorry Problem is still there in 1.14.5

![screenshot_989](https://user-images.githubusercontent.com/2022976/31810589-9e28b130-b57c-11e7-98ab-587764655c54.jpg)

**Comment by moinejf** [comment]
Strange! It works for me, locally and in the public http://moinejf.free.fr/js/edit-1.xhtml.

**Comment by bwl21** [comment]
I see, so i will investigate if something went wrong in my integration.

**Comment by bwl21** [comment]
not sure if you saw my edits of my recent comment. 
I tested again with 1.14.5-5-g531bcb8

Problem is still there

**Comment by moinejf** [comment]
The abc2svg version on my site was not the last one: one commit was lacking (but not the 8155c69).
Anyway, to be sure, I uploaded a new version 1.14.6. This one, as the previous one, does not have your problem.

**Comment by bwl21** [comment]
Now it works fine in http://moinejf.free.fr/js/edit-1.xhtml but still not in Zupfnoter. It does not even work when I pull the script from your website (instead of compiling it myself)

I will track it down and provide feedback. There must be a reason ...

Could it be that there are other dependencies (e.g. jquery) which need to be fulfilled?

It seems a problem with the x-coordinate, since the generated SVG looks like this:

```
<g class="_note_186_187_">
<path class="stroke" d="mNaN 161.00v21.00"/>
<text x="NaN" y="161.00"></text>
</g>
```

**Comment by bwl21** [comment]
There is a method called x_head(s, note)

The situation in my chrome debugger looks like this:
![screenshot_993](https://user-images.githubusercontent.com/2022976/31943027-a11ffb34-b8c7-11e7-8a92-a3bf2c75d86d.jpg)

Don't know if this helps. 

There must be a difference between your website and Zupfnoter. This is, what I am really nervous about.

I initialize abc2svg with 
```
I:titletrim 0
I:measurenb 1
I:contbarnb 1
I:linewarn 0
I:staffnonote 2
```
But this is not the reason, as the problem persists if I remove this. But maybe there is something in your initialization which removes the problem.

**Comment by moinejf** [comment]
From your debugger, the 'x' offset of the note is incorrect (x = NaN).
I found a bug giving such a result when there is no bar at end of line (but not end of tune) and multi-voices.
May you try the last commit?

**Comment by bwl21** [comment]
I tried with 1.14.6-2-g4e5690f. It is getting better but not good.

![screenshot_999](https://user-images.githubusercontent.com/2022976/31955775-b23345a8-b8e9-11e7-8819-5ae3386199ed.jpg)

The stafflines show up when I turn stretchstaff 0

![screenshot_1000](https://user-images.githubusercontent.com/2022976/31955784-b8c361e6-b8e9-11e7-97d8-67b63f37cac5.jpg)

Nevertheless, i do not manage to get exactly the same result in ABC edit and Zupfnoter.

ABC edit yields the following. You see the space difference at the end of the line

![screenshot_1001](https://user-images.githubusercontent.com/2022976/31955841-ea984db2-b8e9-11e7-8862-8972278c846c.jpg)

**Comment by moinejf** [comment]
The strangest is that, as there is only one line, %%stretchstaff should have no impact.
May you check the value of 'x' in set_sym_glue() just before
    if (cfmt.stretchstaff)

**Comment by bwl21** [comment]
![screenshot_1002](https://user-images.githubusercontent.com/2022976/31960243-701a0e5a-b8f7-11e7-8ce3-1acf952ca09b.jpg)

**Comment by moinejf** [comment]
I have x=77.5. There should be some difference about the spacing.
Are you sure the code of music.js is the same?
Otherwise, we may compare the space of all symbols (in fact only 3 are concerned).

**Comment by bwl21** [comment]
if I insert %%stretchstaff i get staff lines. Otherwise there are no stafflines at all.

As soon as i add a bar at the end of the first line, I also have x=77.5. If I add the bar on voice 2 it is 67.5.

This is the rake task which compiles abc2svg. I think music.js is collected by ninja when compiling abc2svg-1.js. So I am pretty sure, that music.js is the one from the repository. I have another rake task which does not compile abc2svg-1 but copies the compiled file from your website. Both approaches yield the same result.

```ruby
desc "Update abc2svg from git clone"
task :updateAbc2svgDev do
  abc2svgrepo = "../../../../200_zupfnoter_external_components/abc2svg"
  abc2svg_file = "abc2svg-1.js"
  sources      = [abc2svg_file, "json-1.js", "midi-1.js"]
  cd abc2svgrepo do
    sources.each {|f| sh  " rm #{f} ; NOMIN=1 ./ninja #{f}"}
  end

  File.open("#{VENDORFOLDER}/#{abc2svg_file}", "w") do |f|
    f.puts "// compiled for Zupfnoter #{Time.now}"
    [sources].flatten.each do |s|
      puts "copying #{s}"
      f.puts File.read("#{abc2svgrepo}/#{s}")
    end
  end


end
```

Would it help if I create a ZIP which you can unpack and serve through a local web server, such that you can debug there.

**Comment by bwl21** [comment]
While preparing the zip-File, I found the difference. I am adding a note after the tune with a checksum of the input file.

```
X:3045
I:stretchstaff 0
F:3045_unreferenced-voices
T:unreferenced voices
C:
S:
M:4/4
L:1/4
Q:1/4=120
K:C
%
%
%%score 1 2 3 4
%
V:1 clef=treble name="Sopran" snm="S"
c
V:2 clef=treble name="Alto" snm="A"
B
V:3 clef=bass name="Tenor" snm="T"
C
V:4 clef=bass name="Bass" snm="B"
%%textoption right
%%textfont * * 8
%%text #{checksum}
```
If I leave out the last three lines, I get x=77.5; (glad that I found the difference :-)

How shall I add such a note such that it does not disturb the rendered notes?

**Comment by moinejf** [comment]
Should be fixed by commit 8399d4d7467f36fbf38e7df4bafeb52fa56d44c1.

**Comment by bwl21** [comment]
Yes, this commit solves the problem. Thanks for your patience and collaboration.
