### ISSUE TITLE
There are Object loops over Array

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#4]
1.13.5 no longer works in Zupfnoter
It does work with 1.12.8

It appears to me that statements like this (object loop applied to array)

```javascript
                for (v in voice_tb) {
                    voice_tb[v].meter = s;
                    voice_tb[v].wmeasure = wmeasure
                }
```

Should iterate over the array elements, but it iterates over the properties of arrays.
It should be:

``` javascript
for(var v = 0; v < voice_tb.length; v++){
                    voice_tb[v].meter = s;
                    voice_tb[v].wmeasure = wmeasure
}

```

This is a general problem with the fact that Opalrb adds more properties to javascript entities.

see also

see https://github.com/opal/opal/issues/1684
https://github.com/opal/opal/issues/680

http://www.sebarmeli.com/blog/2010/12/06/best-way-to-loop-through-an-array-in-javascript/
which says:

> The two main problems with for-in loop are : 
> 1) It enumerates through all the properties even the >ones associated to the
>    Object (that can be augmented previously) 
> 2) The order of the elements i s not guaranteed.
> 
> So it’s strongly recommended to use the FOR LOOP to loop through an Array and remember that
> Java and JavaScript are different.

Would you be able to fix that?

**Comment by bwl21** [comment]
I see that for example in parse.js line 755 of 1.2.9 it was


```javascript
			for (v = 0; v < voice_tb.length; v++) {
				voice_tb[v].meter = s;
				voice_tb[v].wmeasure = wmeasure
			}
```

**Comment by moinejf** [comment]
Should be fixed.
Thanks.

**Comment by bwl21** [comment]
I found one more. This one crashes when I have `I:linebreak $`

abc2svg-1 line 12400
	for (i in param) {


I performed a search but I am not sure if all of those relate to arrays.
If used with objects, it should be qualified with `hasOwnPropery`

```
Targets
    Occurrences of 'for\s*\(\s*[a-zA-Z]+\s*in' in Project
Found Occurrences  (20 usages found)
    Production  (20 usages found)
        Unclassified occurrence  (20 usages found)
            abc2svg-1.js  (7 usages found)
                7551 for (i in info.V)
                12400 for (i in param) {
                12647 for (item in pos)
                14475 for (k in mac) {
                16832 for (opt in parse.voice_opts) {
                16836 for (i in parse.voice_opts[opt])
                17642 for (k in a) {
            edit.js  (1 usage found)
                377 for (o in ref) {
            front.js  (1 usage found)
                656 for (i in info.V)
            json-1.js  (2 usages found)
                104 for (i in val)
                147 for (i in voice_tb[v])
            json.js  (2 usages found)
                84 for (i in val)
                127 for (i in voice_tb[v])
            parse.js  (3 usages found)
                212 for (i in param) {
                459 for (item in pos)
                2287 for (k in mac) {
            psvg.js  (1 usage found)
                255 for (k in obj)
            tune.js  (3 usages found)
                32 for (opt in parse.voice_opts) {
                36 for (i in parse.voice_opts[opt])
                842 for (k in a) {
Usages in generated code  (1 usage found)
    Production  (1 usage found)
        Unclassified occurrence  (1 usage found)
            edit-1.js  (1 usage found)
                1 for(o in

```

**Comment by bwl21** [comment]
I have integrated commit b85eb72.

It works fine. I am still not sure if we caught all the cases. Maybe it is worth to add comment on iterations over hashes just for clarity.

For example I tried to find a test case which covers line parse.js:459 for (item in pos), but I could not.

**Comment by bwl21** [comment]
I integrated 04ee7c6 and tried some of my testcases. It seems to work fine. 

Now it hangs if there is not %%score statement in abc.

**Comment by moinejf** [comment]
On Fri, 11 Aug 2017 11:36:12 +0000 (UTC)
Bernhard Weichel <notifications@github.com> wrote:

> I integrated 04ee7c6 and tried some of my testcases. It seems to work fine. 
> 
> Now it hangs if there is not %%score statement in abc.

Should be fixed by commit bb6cd34d0c546297e97b66da63779540db238dcd

**Comment by bwl21** [comment]
tried with bb6cd34; it no longer hangs with this case.

I now try to run abcnode over all my files. I have another failure. I try to track it down.
